In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
#sentences
sent = [
    'the glass of milk',
    'the glass of blood',
    'the cup of sause',
    'I am the demon',
    'I am the winner',
    'I am the butcher of dreams',
    'understand the meaning of these words',
    'I was always ahead',
]

In [ ]:
sent    

['the glass of milk',
 'the glass of blood',
 'the cup of sause',
 'I am the demon',
 'I am the winner',
 'I am the butcher of dreams',
 'understand the meaning of these words',
 'I was always ahead']

In [4]:
# Vocab_size
voc_size = 10000

In [6]:
#One Hot representation
one_hot_repr = [one_hot(words,voc_size) for words in sent]
one_hot_repr
# Indexes of words described above

[[6913, 8911, 4842, 5089],
 [6913, 8911, 4842, 162],
 [6913, 4501, 4842, 4134],
 [8968, 3662, 6913, 3686],
 [8968, 3662, 6913, 3046],
 [8968, 3662, 6913, 9747, 4842, 8415],
 [5476, 6913, 9190, 4842, 6990, 1310],
 [8968, 9481, 6387, 7878]]

In [14]:
# Word Embeddings
from tensorflow.keras.layers import Embedding,Input
# from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [10]:
# Pad sequence to pad words to make them of equal size --> pre and post in padding for 0s in beg /end
sen_length = 10
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sen_length)
embedded_docs

array([[   0,    0,    0,    0,    0,    0, 6913, 8911, 4842, 5089],
       [   0,    0,    0,    0,    0,    0, 6913, 8911, 4842,  162],
       [   0,    0,    0,    0,    0,    0, 6913, 4501, 4842, 4134],
       [   0,    0,    0,    0,    0,    0, 8968, 3662, 6913, 3686],
       [   0,    0,    0,    0,    0,    0, 8968, 3662, 6913, 3046],
       [   0,    0,    0,    0, 8968, 3662, 6913, 9747, 4842, 8415],
       [   0,    0,    0,    0, 5476, 6913, 9190, 4842, 6990, 1310],
       [   0,    0,    0,    0,    0,    0, 8968, 9481, 6387, 7878]],
      dtype=int32)

In [33]:
embedded_docs.dtype

dtype('int32')

In [11]:
# feature representation ( can keep 300 from google one)
dim =10

In [15]:
model = Sequential()
model.add(Input(shape=(sen_length,)))
model.add(Embedding(input_dim=voc_size,output_dim=dim))
model.compile(optimizer='adam',loss='mse')

In [17]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 10, 10)         │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [18]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step


array([[[ 0.04659149,  0.00565158,  0.02891595, -0.02099391,
         -0.0203874 , -0.01737536, -0.00924347, -0.00726187,
          0.04593966,  0.01188775],
        [ 0.04659149,  0.00565158,  0.02891595, -0.02099391,
         -0.0203874 , -0.01737536, -0.00924347, -0.00726187,
          0.04593966,  0.01188775],
        [ 0.04659149,  0.00565158,  0.02891595, -0.02099391,
         -0.0203874 , -0.01737536, -0.00924347, -0.00726187,
          0.04593966,  0.01188775],
        [ 0.04659149,  0.00565158,  0.02891595, -0.02099391,
         -0.0203874 , -0.01737536, -0.00924347, -0.00726187,
          0.04593966,  0.01188775],
        [ 0.04659149,  0.00565158,  0.02891595, -0.02099391,
         -0.0203874 , -0.01737536, -0.00924347, -0.00726187,
          0.04593966,  0.01188775],
        [ 0.04659149,  0.00565158,  0.02891595, -0.02099391,
         -0.0203874 , -0.01737536, -0.00924347, -0.00726187,
          0.04593966,  0.01188775],
        [-0.04922197,  0.04280311,  0.04149914, -0.0

In [19]:
embedded_docs[0]

array([   0,    0,    0,    0,    0,    0, 6913, 8911, 4842, 5089],
      dtype=int32)

In [34]:
model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step


array([[[ 0.04659149,  0.00565158,  0.02891595, -0.02099391,
         -0.0203874 , -0.01737536, -0.00924347, -0.00726187,
          0.04593966,  0.01188775],
        [ 0.04659149,  0.00565158,  0.02891595, -0.02099391,
         -0.0203874 , -0.01737536, -0.00924347, -0.00726187,
          0.04593966,  0.01188775],
        [ 0.04659149,  0.00565158,  0.02891595, -0.02099391,
         -0.0203874 , -0.01737536, -0.00924347, -0.00726187,
          0.04593966,  0.01188775],
        [ 0.04659149,  0.00565158,  0.02891595, -0.02099391,
         -0.0203874 , -0.01737536, -0.00924347, -0.00726187,
          0.04593966,  0.01188775],
        [ 0.04659149,  0.00565158,  0.02891595, -0.02099391,
         -0.0203874 , -0.01737536, -0.00924347, -0.00726187,
          0.04593966,  0.01188775],
        [ 0.04659149,  0.00565158,  0.02891595, -0.02099391,
         -0.0203874 , -0.01737536, -0.00924347, -0.00726187,
          0.04593966,  0.01188775],
        [-0.04922197,  0.04280311,  0.04149914, -0.0